using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace CollegeManagement.API.DTOs.StudentAdmission
{
    public class CreateStudentAdmissionRequest
    {
        // =========================================================
        // ADMISSION DETAILS
        // =========================================================

        // Generated by backend if not provided.
        public string? AdmissionNo { get; set; }

        [Required]
        public DateTime AdmissionDate { get; set; }

        [MaxLength(50)]
        public string? AdmissionQuota { get; set; }


        // =========================================================
        // STUDENT BASIC DETAILS
        // =========================================================

        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; } = string.Empty;

        [MaxLength(100)]
        public string? LastName { get; set; }

        [Required]
        [MaxLength(20)]
        public string Gender { get; set; } = string.Empty;

        [Required]
        public DateTime DateOfBirth { get; set; }

        [MaxLength(10)]
        public string? BloodGroup { get; set; }

        [EmailAddress]
        [MaxLength(150)]
        public string? Email { get; set; }

        [Phone]
        [MaxLength(20)]
        public string? MobileNumber { get; set; }



        [MaxLength(20)]
        public string? AadhaarNumber { get; set; }

        [MaxLength(50)]
        public string? Nationality { get; set; }

        [MaxLength(50)]
        public string? Religion { get; set; }

        [MaxLength(50)]
        public string? Category { get; set; }


        // =========================================================
        // STUDENT PHOTO
        // =========================================================

        public IFormFile? StudentPhoto { get; set; }


        // =========================================================
        // FATHER DETAILS
        // =========================================================

        [Required]
        [MaxLength(150)]
        public string FatherName { get; set; } = string.Empty;

        [MaxLength(100)]
        public string? FatherOccupation { get; set; }

        [Phone]
        [MaxLength(20)]
        public string? FatherMobile { get; set; }

        [EmailAddress]
        [MaxLength(150)]
        public string? FatherEmail { get; set; }


        // =========================================================
        // MOTHER DETAILS
        // =========================================================

        [Required]
        [MaxLength(150)]
        public string MotherName { get; set; } = string.Empty;

        [MaxLength(100)]
        public string? MotherOccupation { get; set; }

        [Phone]
        [MaxLength(20)]
        public string? MotherMobile { get; set; }

        [EmailAddress]
        [MaxLength(150)]
        public string? MotherEmail { get; set; }


        // =========================================================
        // GUARDIAN DETAILS
        // =========================================================

        [MaxLength(150)]
        public string? GuardianName { get; set; }

        [Phone]
        [MaxLength(20)]
        public string? GuardianMobile { get; set; }

        [EmailAddress]
        [MaxLength(150)]
        public string? GuardianEmail { get; set; }


        // =========================================================
        // INCOME
        // =========================================================

        public decimal? AnnualIncome { get; set; }


        // =========================================================
        // ADDRESS DETAILS
        // =========================================================

        [MaxLength(1000)]
        public string? Address { get; set; }
        [MaxLength(100)]
        public string? City { get; set; }

        [MaxLength(100)]
        public string? District { get; set; }

        [MaxLength(100)]
        public string? State { get; set; }

        [MaxLength(20)]
        public string? Pincode { get; set; }


        // =========================================================
        // ACADEMIC DETAILS
        // =========================================================

        [Required]
        public int BoardId { get; set; }

        [Required]
        public int AcademicYearId { get; set; }

        [Required]
        public int AcademicLevelId { get; set; }

        [Required]
        public int GroupId { get; set; }

        [Required]
        public int SectionId { get; set; }

        [MaxLength(50)]
        public string? Medium { get; set; }

        [MaxLength(50)]
        public string? SecondLanguage { get; set; }

        [MaxLength(50)]
        public string? AdmissionType { get; set; }


        // =========================================================
        // PREVIOUS EDUCATION
        // =========================================================

        [MaxLength(200)]
        public string? PreviousSchool { get; set; }

        public int? PreviousYearOfPassing { get; set; }

        [MaxLength(100)]
        public string? PreviousBoard { get; set; }

        public decimal? PreviousPercentage { get; set; }


        // =========================================================
        // SCHOLARSHIP
        // =========================================================

        [MaxLength(50)]
        public string? ScholarshipStatus { get; set; }


        // =========================================================
        // DOCUMENT UPLOADS
        // =========================================================

        public IFormFile? BirthCertificate { get; set; }

        public IFormFile? TransferCertificate { get; set; }

        public IFormFile? StudyCertificate { get; set; }

        public IFormFile? AadhaarDocument { get; set; }

        public IFormFile? CommunityCertificate { get; set; }

        public IFormFile? IncomeCertificate { get; set; }

        public IFormFile? CasteCertificate { get; set; }

        public IFormFile? TenthCertificate { get; set; }

        public IFormFile? MarksMemo { get; set; }


        // =========================================================
        // REMARKS
        // =========================================================

        [MaxLength(1000)]
        public string? Remarks { get; set; }
    }
}